SYMPTOM_MAP = {
    "Tristeza/Humor depressivo": "1",
    "Desamparo/Prejuízo social/Solidão": "2",
    "Suicídio/Auto-extermínio": "3",
    "Desvalia/Baixa autoestima": "4",
    "Preocupação/Medo/Ansiedade": "5",
    "Desesperança": "6",
    "Alteração na eficiência/funcionalidade": "7",
    "Irritação/Agressividade": "8",
    "Cansaço/Desânimo/Desencorajamento/Fadiga/Perda de energia/Lentificação": "9",
    # "Sentimento de culpa": "10",
    # "Morte/Suicídio de outro": "11",
    # "Perda/diminuição do/da prazer/libido": "12",
    # "Sentimento de vazio": "13",
    # "Dificuldade para decidir": "14",
    # "Alteração de sono": "15",
    # "Sintoma físico": "16",
    # "Alteração de peso/apetite": "17",
    # "Agitação/Inquietação": "18",
    # "Déficit de atenção/memória": "19",
}